spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: IMQ4zyx5C8Ud8ydTKB4y4K4nq7Omyh0i
            client-secret: ZHDwCSyWlZmG_WDGWjdWE2bsgkVFzC13hfFPtTJuCvgsfUXjs0UhmtnjuhER55O0
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-gdp7r5nye12gw6eu.us.auth0.com/